##Analysis of Soil Respiration Anomalies in China's Terrestrial Ecosystems in Response to Extreme Drought Based on Soil Respiration Remote Sensing Data
library(RColorBrewer)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(plotluck)
library(psych)
library(ggthemes)
library(tidyverse)
library(Rmisc)
library(readr)
library(ggsci)
library(gridExtra)
library(ggpmisc)
library(wesanderson)
library(viridis)
library(cowplot)
library(lme4)
library(sjmisc)
library(effects)
library(sjstats)
library(lmerTest)
library(MuMIn)
library(Matrix)
China_rs <- read.csv("E:\\RP\\TFR_RSanomaly&SPEI_20231108.csv")
glimpse(China_rs , width = 40)

p <- ggplot(China_rs, aes(x = SPEI, y = RS_anomaly)) + geom_point(size=2,aes(color=Vegetation),alpha = 0.3) + geom_smooth(method = 'lm', se = TRUE, show.legend = FALSE) + theme_bw() + theme(axis.title.x =element_text(size=17), axis.title.y=element_text(size=17),axis.text=element_text(size=14,family ="Times", face = "plain"))
p

ggsave("Soil Respiration Anomalies in Response to Extreme Drought Based on Soil Respiration Remote Sensing Data.tiff",width=180, height=140, units="mm", dpi=800)


m0 <- lmer(RS_anomaly ~ SPEI + (1 | LAT) + (1 | LON) , data = China_rs)
summary(m0)
r.squaredGLMM(m0)